version: "3"
name: extractor
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      HOST: "0.0.0.0"
      PORT: "4321"
    restart: always

  nginx:
    image: nginx:latest
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    restart: always
